services:
    postgres:
        container_name: postgres
        image: 'postgres:latest'
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - pgdata:/var/lib/posgresql/data
#    inven3:
#        build: .
#        environment:
#            - 'POSTGRES_DB=${POSTGRES_DB}'
#            - 'POSTGRES_USER=${POSTGRES_USER}'
#            - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
#        ports:
#            - '8080'

volumes:
    pgdata:
